### ISSUE TITLE
I think you are looking for octo:

### ISSUE THREAD

**Issue by jmbuhr** [dundargoc/gh.nvim#1]
https://github.com/pwntester/octo.nvim

**Comment by dundargoc** [comment]
Yes but it doesn't adhere to the Unix philosophy, or something.

**Comment by dundargoc** [comment]
Basically I need to write some plugins to learn how to write plugins, and this seemed like a decent idea. Thanks for the tip though, will check it out!

**Comment by jmbuhr** [comment]
Ah, right, I just saw your plugin guide PR for neovim. Looking forward to it!
